openapi: 3.0.3

servers:
  - url: http://localhost:3000
paths:
  /posts:
    get:
      summary: get posts
      description: Returns all posts
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Post title
        created_at:
          type: string
          example: 2023-01-01T00:00:00.000Z
        updated_at:
          type: string
          example: 2023-01-02T00:00:00.000Z
      required:
        - id
        - name
        - created_at
        - updated_at

